# Generated by Django 6.0.3 on 2026-04-16 23:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cursos',
            fields=[
                ('curso_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_curso', models.CharField(max_length=100)),
                ('categoria', models.CharField(max_length=100)),
                ('cupo_maximo', models.IntegerField(default=5)),
                ('duracion_horas', models.IntegerField()),
                ('costo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], max_length=20)),
            ],
            options={
                'db_table': 'Cursos',
            },
        ),
        migrations.CreateModel(
            name='Estudiantes',
            fields=[
                ('estudiante_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_completo', models.CharField(max_length=100)),
                ('email', models.BinaryField(max_length='max')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('direccion', models.CharField(blank=True, max_length=150, null=True)),
                ('tipo_documento', models.CharField(max_length=20)),
                ('numero_documento', models.BinaryField(max_length='max')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Estudiantes',
            },
        ),
        migrations.CreateModel(
            name='Instructores',
            fields=[
                ('instructor_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_completo', models.CharField(max_length=100)),
                ('especialidad', models.CharField(blank=True, max_length=50, null=True)),
                ('cedula_profesional', models.BinaryField(max_length='max')),
                ('usuario', models.CharField(max_length=50, unique=True)),
                ('contrasena', models.BinaryField(max_length='max')),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], max_length=20)),
            ],
            options={
                'db_table': 'Instructores',
            },
        ),
        migrations.CreateModel(
            name='MetodosPago',
            fields=[
                ('metodo_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'db_table': 'MetodosPago',
            },
        ),
        migrations.CreateModel(
            name='Inscripciones',
            fields=[
                ('inscripcion_id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inscripcion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('cancelada', 'Cancelada'), ('finalizada', 'Finalizada')], max_length=20)),
                ('total_pago', models.DecimalField(decimal_places=2, max_digits=10)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mi_app.cursos')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mi_app.estudiantes')),
            ],
            options={
                'db_table': 'Inscripciones',
            },
        ),
        migrations.CreateModel(
            name='Evaluaciones',
            fields=[
                ('evaluacion_id', models.AutoField(primary_key=True, serialize=False)),
                ('calificacion', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('comentarios', models.BinaryField(blank=True, max_length='max', null=True)),
                ('tipo_evaluacion', models.CharField(choices=[('parcial', 'Parcial'), ('final', 'Final')], default='final', max_length=50)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('inscripcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mi_app.inscripciones')),
                ('instructor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mi_app.instructores')),
            ],
            options={
                'db_table': 'Evaluaciones',
            },
        ),
        migrations.CreateModel(
            name='Pagos',
            fields=[
                ('pago_id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_pago', models.DateTimeField(auto_now_add=True)),
                ('referencia_pago', models.BinaryField(blank=True, max_length='max', null=True)),
                ('monto', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('inscripcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mi_app.inscripciones')),
                ('metodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mi_app.metodospago')),
            ],
            options={
                'db_table': 'Pagos',
            },
        ),
        migrations.CreateModel(
            name='DetallePago',
            fields=[
                ('detalle_id', models.AutoField(primary_key=True, serialize=False)),
                ('concepto', models.CharField(max_length=100)),
                ('cantidad', models.IntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mi_app.pagos')),
            ],
            options={
                'db_table': 'Detalle_Pago',
            },
        ),
        migrations.CreateModel(
            name='CursoInstructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mi_app.cursos')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mi_app.instructores')),
            ],
            options={
                'db_table': 'Curso_Instructor',
                'unique_together': {('curso', 'instructor')},
            },
        ),
    ]
